module.exports = {
  DATA_NOT_FOUND: "Data not found.",
  ALREADY_REGISTER: "User already register.",
  REGISTER_SUCCESSFULLY: "Register Successfully ",
  PASSWORD_NOT_UPDATED: "Password not Updated",
  LOGIN_SUCCESSFULLY: "login successfully.",
  INVALID_APPLICATION_NUMBER: "Invalid Application Number",
  NOT_ALLOW: "Not allow.",
  ERROR: "Error",
  USER_NOT_FOUND: "User not found",
  INVALID: "Invalid.",
  SERVER_ERROR: "Server Error",
  NOT_UPDATED:'Not Updated',
  UPDATE_DATA: "updated.",
  ALREADY_EXIST: "already exist.",
  ADDED_SUCCESSFULLY: "added successfully",
  ENTER_DATA: "Enter data.",
  PORT: 3000,
};
